[tool.poetry]
name = "sortingvisualization"
version = "0.1.0"
description = "A simple visualization of different sorting algorithms"
authors = ["Nico Riedl"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pygame = "2.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"